version: '3'
services:
  ws_dash:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules  # To prevent overwriting node_modules if installed in the container
    ports:
      - "3000:3000"
      - "8080:8080"
    restart: always
    environment:
      - NODE_ENV=development
